
  
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1112/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 8082




management: 
  security:
    enabled: false

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false

#mongodb
spring:
 data:
  mongodb:
   host : localhost
   port : 27017
   database : RegionDB
message : Hello Sadun

#logging
logging.level.org.springframework.data : debug
logging.level. : info
